# Generated by Django 5.1.4 on 2024-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='description',
        ),
        migrations.AddField(
            model_name='advantage',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
