# Generated by Django 5.1.4 on 2024-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_advantage_description_advantage_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
