# Generated by Django 5.1.4 on 2024-12-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_advantage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
