# Generated by Django 5.1.4 on 2024-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advantage',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
